name: Test

on:
  push:
    branches:
      - python

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install EnhanceDocs CLI
        uses: enhancedocs/setup-enhancedocs@b278ff542335737822d6917fb38b3e2e049a56cd
        with:
          # More about EnhanceDocs Secret API Key: https://docs.enhancedocs.com/security/api-keys
          api-key: ${{ secrets.ENHANCEDOCS_API_KEY }}

      - name: Version
        run: enhancedocs --version
