name: Test

on:
  push:
    branches:
      - python

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install EnhanceDocs CLI
        uses: enhancedocs/setup-enhancedocs@6259d79bc7fae604751e713a6f5b4cb2bd9ff5d2
        with:
          # More about EnhanceDocs Secret API Key: https://docs.enhancedocs.com/security/api-keys
          api-key: ${{ secrets.ENHANCEDOCS_API_KEY }}

      - name: Version
        run: enhancedocs --version
